n = int(input())
m = int(input())
k = int(input())
x = int(input())
y = int(input())
z = int(input())
t = int(input())
a = int(input())
print(n - t - (z - (z - n) - (z - k) - t) - (m - (x - n) - t) + m - t - (m - (x - n) - t) - (
        x - (y - k) - (x - m) - t) + k - t - (z - (z - n) - (z - k) - t) - (x - (y - k) - (x - m) - t))
print((z - (z - n) - (z - k) - t) + (m - (x - n) - t) + (x - (y - k) - (x - m) - t))
print(a - y - (n - t - (z - (z - n) - (z - k) - t) - (m - (x - n) - t)))
